### ISSUE TITLE
The grid assumes all direct decedents are 100% width

### ISSUE THREAD

**Issue by AlexOverbeck** [mobi/gosheets#16]
Currently, our grid assumes that everything that is a direct descendent of a `.grid-column` should take up 100% the width of said column. This assumption leads to misleading results, especially when working with forms.

```scss
.go-column {
  flex: 1 1 auto;
  padding: 0 $column-gutter $column-gutter--double;

  > *:not(.go-container) {
    width: 100%;
  }
}
```

I think we should either remove this style or we should introduce a mechanism to control it.
